### ISSUE TITLE
変更が反映されない

### ISSUE THREAD

**Issue by nikolat** [mattn/nostr-webhook#1]
hook.html にて、Nameに半角括弧`()`を使用した名前を登録して新規作成すると、
その後その項目を編集して保存しようとしても変更が反映されません。

**Comment by mattn** [comment]
ありがとうございます。どうも ORM が起因してそうなのですが、原因が特定できていないので、いったん `xxx(yyy)` を `xxx-yyy` に変更させて頂きました。別途解析して修正します。

**Comment by mattn** [comment]
あー、原因分かりました。(僕のバグでした)

**Comment by mattn** [comment]
fixed https://github.com/mattn/nostr-webhook/commit/f40c78097c79d6b98a75ee0ad824b47569c15a0c
